In [7]:
import numpy as np

In [2]:
lst = [1,2,3]
type(lst)

list

**Convert list to numpy array**

In [8]:
np_array = np.array(lst)
np_array

array([1, 2, 3])

In [5]:
print(np_array)

[1 2 3]


In [6]:
type(np_array)

numpy.ndarray

In [12]:
m_lst = [ [1,2,3,4], [3,5,6,7], [2,8,9,10]]

In [13]:
m_array = np.array(m_lst)
m_array

array([[ 1,  2,  3,  4],
       [ 3,  5,  6,  7],
       [ 2,  8,  9, 10]])

**for dimension , use shape**

In [14]:
m_array.shape

(3, 4)

**Reshape**

In [18]:
m_array = np.reshape(m_array, (4,3))
m_array

array([[ 1,  2,  3],
       [ 4,  3,  5],
       [ 6,  7,  2],
       [ 8,  9, 10]])

In [17]:
m_array.shape

(4, 3)

**Creating an array of zeroes only**

In [20]:
np.zeros( (14,30), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

**Creating an array of ones only**

In [21]:
np.ones((12,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
rand = np.random.randint(0,10)
print(rand)

6


In [28]:
np.linspace(2,10)        # deafult it will generate 50 numbers between 2 and 10

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [31]:
np_ln = np.linspace(2,10, 14)  
np_ln

array([ 2.        ,  2.61538462,  3.23076923,  3.84615385,  4.46153846,
        5.07692308,  5.69230769,  6.30769231,  6.92307692,  7.53846154,
        8.15384615,  8.76923077,  9.38461538, 10.        ])

In [32]:
np.mean(np_ln)

6.000000000000001

In [33]:
np.sqrt(np_ln)

array([1.41421356, 1.61721508, 1.79743407, 1.96116135, 2.11223542,
       2.25320285, 2.38585576, 2.51151196, 2.63117406, 2.74562589,
       2.85549403, 2.9612887 , 3.06343196, 3.16227766])

In [34]:
np_ln + 2         # can perform arithmetic operations

array([ 4.        ,  4.61538462,  5.23076923,  5.84615385,  6.46153846,
        7.07692308,  7.69230769,  8.30769231,  8.92307692,  9.53846154,
       10.15384615, 10.76923077, 11.38461538, 12.        ])

# PANDAS

In [38]:
import pandas as pd

In [43]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In [62]:
type(df)

pandas.core.frame.DataFrame

In [44]:
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [54]:
df.shape

(17000, 9)

In [45]:
df['longitude']

0       -114.31
1       -114.47
2       -114.56
3       -114.57
4       -114.57
          ...  
16995   -124.26
16996   -124.27
16997   -124.30
16998   -124.30
16999   -124.35
Name: longitude, Length: 17000, dtype: float64

In [46]:
type(df['longitude'])

pandas.core.series.Series

**To convert one df column into array**

In [51]:
longitude = df['longitude'].values
longitude

array([-114.31, -114.47, -114.56, ..., -124.3 , -124.3 , -124.35])

In [52]:
type(longitude)

numpy.ndarray

In [53]:
len(longitude)

17000

**Convert whole df into array**

In [56]:
data = df.values
data

array([[-1.1431e+02,  3.4190e+01,  1.5000e+01, ...,  4.7200e+02,
         1.4936e+00,  6.6900e+04],
       [-1.1447e+02,  3.4400e+01,  1.9000e+01, ...,  4.6300e+02,
         1.8200e+00,  8.0100e+04],
       [-1.1456e+02,  3.3690e+01,  1.7000e+01, ...,  1.1700e+02,
         1.6509e+00,  8.5700e+04],
       ...,
       [-1.2430e+02,  4.1840e+01,  1.7000e+01, ...,  4.5600e+02,
         3.0313e+00,  1.0360e+05],
       [-1.2430e+02,  4.1800e+01,  1.9000e+01, ...,  4.7800e+02,
         1.9797e+00,  8.5800e+04],
       [-1.2435e+02,  4.0540e+01,  5.2000e+01, ...,  2.7000e+02,
         3.0147e+00,  9.4600e+04]])

In [57]:
data[:,:]

array([[-1.1431e+02,  3.4190e+01,  1.5000e+01, ...,  4.7200e+02,
         1.4936e+00,  6.6900e+04],
       [-1.1447e+02,  3.4400e+01,  1.9000e+01, ...,  4.6300e+02,
         1.8200e+00,  8.0100e+04],
       [-1.1456e+02,  3.3690e+01,  1.7000e+01, ...,  1.1700e+02,
         1.6509e+00,  8.5700e+04],
       ...,
       [-1.2430e+02,  4.1840e+01,  1.7000e+01, ...,  4.5600e+02,
         3.0313e+00,  1.0360e+05],
       [-1.2430e+02,  4.1800e+01,  1.9000e+01, ...,  4.7800e+02,
         1.9797e+00,  8.5800e+04],
       [-1.2435e+02,  4.0540e+01,  5.2000e+01, ...,  2.7000e+02,
         3.0147e+00,  9.4600e+04]])

In [60]:
data[:3,:]    #[rows, columns]

array([[-1.1431e+02,  3.4190e+01,  1.5000e+01,  5.6120e+03,  1.2830e+03,
         1.0150e+03,  4.7200e+02,  1.4936e+00,  6.6900e+04],
       [-1.1447e+02,  3.4400e+01,  1.9000e+01,  7.6500e+03,  1.9010e+03,
         1.1290e+03,  4.6300e+02,  1.8200e+00,  8.0100e+04],
       [-1.1456e+02,  3.3690e+01,  1.7000e+01,  7.2000e+02,  1.7400e+02,
         3.3300e+02,  1.1700e+02,  1.6509e+00,  8.5700e+04]])

In [61]:
data[:3, :3]

array([[-114.31,   34.19,   15.  ],
       [-114.47,   34.4 ,   19.  ],
       [-114.56,   33.69,   17.  ]])